version: 2
project_name: bgit
release:
  github:
    owner: jplindgren
    name: bastard-git
  changelog:
    use: github
builds:
  - main: make build
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archive:
  format: tar.gz
  files:
    - LICENSE
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
signs:
  - artifacts: checksum
    args: ['--armor', '--detach-sign', '--output={{ .Artifact }}.sig']
